"""Render records as data.sql rows and as PlanetScale console statements.

Nothing here writes into the repository or the database. Everything lands in
out/ for a human to read, diff and paste.
"""
import json, os

from .mapping import UNKNOWN

COLUMNS = ["id", "plan_group_id", "plan_name", "cms_plan_id", "plan_year",
           "benefits_published", "monthly_premium", "moop", "plan_type",
           "dr_visit", "er_visit", "hospital_stay", "hospital_stay_length",
           "surgery_min", "surgery_max", "surgery_copay_type",
           "radiology_copay_min", "radiology_copay_max", "radiology_coinsurance",
           "dental_benefit", "otc_credit", "otc_renewal", "giveback_amount",
           "rx_coverage", "company_id"]

# Placeholder written for a column CMS did not supply. The row is emitted with
# benefits_published = false, so the UI shows N/A rather than this number.
UNKNOWN_FILL = {"otc_renewal": '"None"', "plan_type": '"UNKNOWN"'}


def _sql(column, value):
    if value is UNKNOWN:
        return UNKNOWN_FILL.get(column, "0")
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return '"%s"' % value.replace('"', '')
    if isinstance(value, float):
        return "%.2f" % value
    return str(value)


def _unknown_columns(record):
    return sorted(c for c, v in record.items() if v is UNKNOWN)


def write_all(out_dir, year, records, areas, identity, counties):
    os.makedirs(out_dir, exist_ok=True)
    written = []

    # Deterministic ids: sorted CMS plan id, offset by year so a rerun with the
    # same inputs produces the same file.
    keys = sorted(records)
    id_of = {key: 1000 + (year % 100) * 100 + i for i, key in enumerate(keys, 1)}

    rows, unknown_report = [], {}
    for key in keys:
        record = records[key]
        unknowns = _unknown_columns(record)
        if unknowns:
            unknown_report[key] = unknowns
        row = {
            "id": id_of[key],
            "plan_group_id": id_of[key],
            "plan_name": (identity.get(key, {}).get("plan_name") or key),
            "cms_plan_id": key,
            "plan_year": year,
            # Never publish a row that still has an unknown benefit.
            "benefits_published": not unknowns,
            "company_id": 0,
        }
        row.update({c: record.get(c, UNKNOWN) for c, in ((c,) for c in COLUMNS)
                    if c in record})
        rows.append(row)

    # ---- data.sql fragment -------------------------------------------------
    path = os.path.join(out_dir, "plans-%d.sql" % year)
    with open(path, "w") as fh:
        fh.write("-- Generated by tools/plan-importer for plan year %d.\n" % year)
        fh.write("-- Review before merging. company_id is 0 and plan_name is the raw\n")
        fh.write("-- CMS marketing name -- both need a human decision.\n\n")
        cols = ", ".join(COLUMNS)
        for row in rows:
            values = ", ".join(_sql(c, row.get(c, UNKNOWN)) for c in COLUMNS)
            fh.write("INSERT INTO plan (%s\n) VALUES (\n  %s\n);\n" % (cols, values))
        fh.write("\n-- county availability\n")
        for key in keys:
            for county in sorted(areas.get(key, ())):
                fh.write("-- %s -> %s (county_id must be filled in)\n" % (key, county))
    written.append(path)

    # ---- PlanetScale console statements, one per line ----------------------
    path = os.path.join(out_dir, "planetscale-%d.sql" % year)
    with open(path, "w") as fh:
        fh.write("-- One statement per line: the PlanetScale console runs them\n")
        fh.write("-- one at a time. DML -- run directly, not as a deploy request.\n\n")
        for row in rows:
            values = ", ".join(_sql(c, row.get(c, UNKNOWN)) for c in COLUMNS)
            fh.write("INSERT INTO `plan` (%s) VALUES (%s);\n" % (", ".join(COLUMNS), values))
    written.append(path)

    # ---- what still needs a human ------------------------------------------
    path = os.path.join(out_dir, "unknowns-%d.json" % year)
    with open(path, "w") as fh:
        json.dump({"plans_with_unknowns": len(unknown_report),
                   "total_plans": len(rows),
                   "detail": unknown_report}, fh, indent=2)
    written.append(path)
    return written
